language: objective-c
before_script:
    - brew update
    - brew install xctool && brew cleanup xctool
script:
    - xctool -project NitroNSDictionaryCategories/NitroNSDictionaryCategories.xcodeproj -sdk iphonesimulator -scheme NitroNSDictionaryCategories test
